env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-plusplus: off
  no-use-before-define: warn
  no-await-in-loop: warn
  wrap-iife: off
  import/prefer-default-export: off
  max-len: [warn, 132]
